export const dataMok = [
  {
    posicao: 1,
    pontos: 81,
    time: {
      time_id: 56,
      nome_popular: 'Palmeiras',
      sigla: 'PAL',
      escudo: 'https://cdn.api-futebol.com.br/escudos/638d34a1cf247.svg',
    },
    jogos: 38,
    vitorias: 23,
    empates: 12,
    derrotas: 3,
    gols_pro: 66,
    gols_contra: 27,
    saldo_gols: 39,
    aproveitamento: 71,
    variacao_posicao: 0,
    ultimos_jogos: ['v', 'v', 'e', 'v', 'd'],
  },
  {
    posicao: 2,
    pontos: 73,
    time: {
      time_id: 44,
      nome_popular: 'Internacional',
      sigla: 'INT',
      escudo: 'https://cdn.api-futebol.com.br/escudos/638d349b92103.svg',
    },
    jogos: 38,
    vitorias: 20,
    empates: 13,
    derrotas: 5,
    gols_pro: 58,
    gols_contra: 31,
    saldo_gols: 27,
    aproveitamento: 64,
    variacao_posicao: 0,
    ultimos_jogos: ['v', 'd', 'v', 'v', 'v'],
  },
  {
    posicao: 3,
    pontos: 70,
    time: {
      time_id: 26,
      nome_popular: 'Fluminense',
      sigla: 'FLU',
      escudo: 'https://cdn.api-futebol.com.br/escudos/638d3492a6e0b.svg',
    },
    jogos: 38,
    vitorias: 21,
    empates: 7,
    derrotas: 10,
    gols_pro: 63,
    gols_contra: 41,
    saldo_gols: 22,
    aproveitamento: 61,
    variacao_posicao: 0,
    ultimos_jogos: ['v', 'v', 'v', 'v', 'v'],
  },
  {
    posicao: 4,
    pontos: 65,
    time: {
      time_id: 65,
      nome_popular: 'Corinthians',
      sigla: 'COR',
      escudo: 'https://cdn.api-futebol.com.br/escudos/638d34a68419f.svg',
    },
    jogos: 38,
    vitorias: 18,
    empates: 11,
    derrotas: 9,
    gols_pro: 44,
    gols_contra: 36,
    saldo_gols: 8,
    aproveitamento: 57,
    variacao_posicao: 0,
    ultimos_jogos: ['d', 'v', 'v', 'e', 'd'],
  },
  {
    posicao: 5,
    pontos: 62,
    time: {
      time_id: 18,
      nome_popular: 'Flamengo',
      sigla: 'FLA',
      escudo: 'https://cdn.api-futebol.com.br/escudos/638d348e3f815.svg',
    },
    jogos: 38,
    vitorias: 18,
    empates: 8,
    derrotas: 12,
    gols_pro: 60,
    gols_contra: 39,
    saldo_gols: 21,
    aproveitamento: 54,
    variacao_posicao: 0,
    ultimos_jogos: ['v', 'd', 'd', 'e', 'd'],
  },
  {
    posicao: 6,
    pontos: 58,
    time: {
      time_id: 185,
      nome_popular: 'Athletico-PR',
      sigla: 'CAP',
      escudo: 'https://cdn.api-futebol.com.br/escudos/638d34e1b8948.svg',
    },
    jogos: 38,
    vitorias: 16,
    empates: 10,
    derrotas: 12,
    gols_pro: 48,
    gols_contra: 48,
    saldo_gols: 0,
    aproveitamento: 50,
    variacao_posicao: 0,
    ultimos_jogos: ['d', 'v', 'd', 'e', 'v'],
  },
  {
    posicao: 7,
    pontos: 58,
    time: {
      time_id: 30,
      nome_popular: 'Atlético-MG',
      sigla: 'CAM',
      escudo: 'https://cdn.api-futebol.com.br/escudos/638d3494f3380.svg',
    },
    jogos: 38,
    vitorias: 15,
    empates: 13,
    derrotas: 10,
    gols_pro: 45,
    gols_contra: 37,
    saldo_gols: 8,
    aproveitamento: 50,
    variacao_posicao: 0,
    ultimos_jogos: ['v', 'e', 'd', 'v', 'v'],
  },
  {
    posicao: 8,
    pontos: 55,
    time: {
      time_id: 131,
      nome_popular: 'Fortaleza',
      sigla: 'FOR',
      escudo: 'https://cdn.api-futebol.com.br/escudos/638d34c76d067.svg',
    },
    jogos: 38,
    vitorias: 15,
    empates: 10,
    derrotas: 13,
    gols_pro: 46,
    gols_contra: 39,
    saldo_gols: 7,
    aproveitamento: 48,
    variacao_posicao: 2,
    ultimos_jogos: ['v', 'd', 'e', 'v', 'v'],
  },
  {
    posicao: 9,
    pontos: 54,
    time: {
      time_id: 57,
      nome_popular: 'São Paulo',
      sigla: 'SAO',
      escudo: 'https://cdn.api-futebol.com.br/escudos/638d34a23c311.svg',
    },
    jogos: 38,
    vitorias: 13,
    empates: 15,
    derrotas: 10,
    gols_pro: 55,
    gols_contra: 42,
    saldo_gols: 13,
    aproveitamento: 47,
    variacao_posicao: 2,
    ultimos_jogos: ['v', 'e', 'd', 'd', 'v'],
  },
  {
    posicao: 10,
    pontos: 53,
    time: {
      time_id: 33,
      nome_popular: 'América-MG',
      sigla: 'AMG',
      escudo: 'https://cdn.api-futebol.com.br/escudos/638d34966e9c6.svg',
    },
    jogos: 38,
    vitorias: 15,
    empates: 8,
    derrotas: 15,
    gols_pro: 40,
    gols_contra: 40,
    saldo_gols: 0,
    aproveitamento: 46,
    variacao_posicao: -1,
    ultimos_jogos: ['e', 'v', 'v', 'd', 'e'],
  },
  {
    posicao: 11,
    pontos: 53,
    time: {
      time_id: 22,
      nome_popular: 'Botafogo',
      sigla: 'BOT',
      escudo: 'https://cdn.api-futebol.com.br/escudos/638d349052558.svg',
    },
    jogos: 38,
    vitorias: 15,
    empates: 8,
    derrotas: 15,
    gols_pro: 41,
    gols_contra: 43,
    saldo_gols: -2,
    aproveitamento: 46,
    variacao_posicao: -3,
    ultimos_jogos: ['v', 'd', 'v', 'v', 'd'],
  },
  {
    posicao: 12,
    pontos: 47,
    time: {
      time_id: 63,
      nome_popular: 'Santos',
      sigla: 'SAN',
      escudo: 'https://cdn.api-futebol.com.br/escudos/638d34a5749d6.svg',
    },
    jogos: 38,
    vitorias: 12,
    empates: 11,
    derrotas: 15,
    gols_pro: 44,
    gols_contra: 41,
    saldo_gols: 3,
    aproveitamento: 41,
    variacao_posicao: 0,
    ultimos_jogos: ['d', 'v', 'e', 'd', 'd'],
  },
  {
    posicao: 13,
    pontos: 46,
    time: {
      time_id: 115,
      nome_popular: 'Goiás',
      sigla: 'GOI',
      escudo: 'https://cdn.api-futebol.com.br/escudos/638d34c1c1d9f.svg',
    },
    jogos: 38,
    vitorias: 11,
    empates: 13,
    derrotas: 14,
    gols_pro: 40,
    gols_contra: 53,
    saldo_gols: -13,
    aproveitamento: 40,
    variacao_posicao: 0,
    ultimos_jogos: ['e', 'd', 'v', 'd', 'd'],
  },
  {
    posicao: 14,
    pontos: 44,
    time: {
      time_id: 64,
      nome_popular: 'Bragantino',
      sigla: 'BGT',
      escudo: 'https://cdn.api-futebol.com.br/escudos/638d34a5db2ec.svg',
    },
    jogos: 38,
    vitorias: 11,
    empates: 11,
    derrotas: 16,
    gols_pro: 49,
    gols_contra: 59,
    saldo_gols: -10,
    aproveitamento: 38,
    variacao_posicao: 0,
    ultimos_jogos: ['d', 'v', 'd', 'd', 'd'],
  },
  {
    posicao: 15,
    pontos: 42,
    time: {
      time_id: 84,
      nome_popular: 'Coritiba',
      sigla: 'CFC',
      escudo: 'https://cdn.api-futebol.com.br/escudos/638d34b1296c2.svg',
    },
    jogos: 38,
    vitorias: 12,
    empates: 6,
    derrotas: 20,
    gols_pro: 39,
    gols_contra: 60,
    saldo_gols: -21,
    aproveitamento: 36,
    variacao_posicao: 0,
    ultimos_jogos: ['d', 'v', 'v', 'e', 'd'],
  },
  {
    posicao: 16,
    pontos: 41,
    time: {
      time_id: 204,
      nome_popular: 'Cuiabá',
      sigla: 'CUI',
      escudo: 'https://cdn.api-futebol.com.br/escudos/638d34ebcdafa.svg',
    },
    jogos: 38,
    vitorias: 10,
    empates: 11,
    derrotas: 17,
    gols_pro: 31,
    gols_contra: 42,
    saldo_gols: -11,
    aproveitamento: 35,
    variacao_posicao: 0,
    ultimos_jogos: ['v', 'v', 'e', 'd', 'v'],
  },
  {
    posicao: 17,
    pontos: 37,
    time: {
      time_id: 105,
      nome_popular: 'Ceará',
      sigla: 'CEA',
      escudo: 'https://cdn.api-futebol.com.br/escudos/638d34bcb81bc.svg',
    },
    jogos: 38,
    vitorias: 7,
    empates: 16,
    derrotas: 15,
    gols_pro: 34,
    gols_contra: 41,
    saldo_gols: -7,
    aproveitamento: 32,
    variacao_posicao: 1,
    ultimos_jogos: ['d', 'd', 'd', 'd', 'v'],
  },
  {
    posicao: 18,
    pontos: 36,
    time: {
      time_id: 98,
      nome_popular: 'Atlético-GO',
      sigla: 'ACG',
      escudo: 'https://cdn.api-futebol.com.br/escudos/638d34b9174a3.svg',
    },
    jogos: 38,
    vitorias: 8,
    empates: 12,
    derrotas: 18,
    gols_pro: 39,
    gols_contra: 57,
    saldo_gols: -18,
    aproveitamento: 31,
    variacao_posicao: -1,
    ultimos_jogos: ['d', 'd', 'e', 'e', 'e'],
  },
  {
    posicao: 19,
    pontos: 35,
    time: {
      time_id: 6,
      nome_popular: 'Avaí',
      sigla: 'AVA',
      escudo: 'https://cdn.api-futebol.com.br/escudos/638d3487aa471.svg',
    },
    jogos: 38,
    vitorias: 9,
    empates: 8,
    derrotas: 21,
    gols_pro: 34,
    gols_contra: 60,
    saldo_gols: -26,
    aproveitamento: 30,
    variacao_posicao: 0,
    ultimos_jogos: ['d', 'd', 'e', 'v', 'v'],
  },
  {
    posicao: 20,
    pontos: 22,
    time: {
      time_id: 43,
      nome_popular: 'Juventude',
      sigla: 'JUV',
      escudo: 'https://cdn.api-futebol.com.br/escudos/638d349b308c6.svg',
    },
    jogos: 38,
    vitorias: 3,
    empates: 13,
    derrotas: 22,
    gols_pro: 29,
    gols_contra: 69,
    saldo_gols: -40,
    aproveitamento: 19,
    variacao_posicao: 0,
    ultimos_jogos: ['d', 'd', 'd', 'e', 'd'],
  },
]
